# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_version = "20190209.0.0"
  config.vm.synced_folder "..", "/vagrant"
  config.vm.network "private_network", ip: "192.168.50.5"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1536"
    vb.linked_clone = true if Vagrant::VERSION >= "1.8"
    vb.customize ['modifyvm', :id, '--paravirtprovider', 'kvm']
    vb.customize ["modifyvm", :id, "--audio", "none"]
  end

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
    config.cache.enable :apt
    config.cache.synced_folder_opts = {
      owner: "_apt"
    }
  end

end
